### ISSUE TITLE
How to get Apache BVal listed as 1.1 certified?

### ISSUE THREAD

**Issue by rmannibucau** [beanvalidation/beanvalidation.org#35]
Hi,

Apache BVal passes bean validation 1.1 TCK since months but is not listed on http://beanvalidation.org/1.1/certified/

what is involed to get there, any blocker/reason?

If needed:
- logo: http://bval.apache.org//resources/images/bval-bean-small.png
- name: Apache BVal
- version: 1.1.1
- url: http://bval.apache.org/

Thanks,
Romain

**Comment by gunnarmorling** [comment]
Hey @rmannibucau, no reason really, we just haven't been aware of this. Also seeing it was missing, I actually was just asking Matt and Gerhard about this recently and they were not sure 100% either.

Do you have some pointers to how the TCK was run (which server, result logs etc.)? Did you also run the signature test? The TCK [reference guide](http://docs.jboss.org/hibernate/beanvalidation/tck/1.1/reference/html_single/#passing-the-tck) has all the details if needed. Essentially it'd be great to have some details/results of the TCK run or even actually some set-up (e.g. based on the example provided with the TCK) allowing to reproduce it.

Congrats btw. for passing it, very nice to have to compatible impls with that!

**Comment by rmannibucau** [comment]
Hi @gunnarmorling

Here is bval / standalone run: https://github.com/apache/bval/tree/trunk/bval-tck11
Here is the one for tomee: https://github.com/apache/tomee/tree/master/tck/bval-tomee (there is a bval-embedded for openejb without tomee too but not sure it is important). You can see the result browsing test step of https://ci.apache.org/builders/tomee-trunk-ubuntu/builds/524 - we run tck with each build

Iirc i ran signature test against geronimo api jar (used in tomee too) but can do again if needed - makes months now ;).

**Comment by gunnarmorling** [comment]
Hi @rmannibucau, finally circling back to this one. Sorry for the long delay on my end. I forked that set-up from https://github.com/apache/tomee/tree/master/tck/bval-tomee and all tests pass.

But which API JAR is this using? I couldn't find any (neither _validation-api_ nor the Geronimo one) under _target/tomee-tck/apache-tomee-webprofile-7.0.2-SNAPSHOT/lib_. I had assumed the Geronimo one would be used? Thanks for any pointers!

**Comment by rmannibucau** [comment]
Hi @gunnarmorling, yes geronimo one but we do a "all in one EE bundle" for tomee named javaee-api

**Comment by gunnarmorling** [comment]
Thanks for the quick reply! Could run it now, and there is one diff in the signatures:

```
Added Annotations
-----------------

javax.validation.ConstraintValidatorContext$ConstraintViolationBuilder:         addNode(java.lang.String):anno 0 java.lang.Deprecated()
javax.validation.ConstraintValidatorContext$ConstraintViolationBuilder$NodeBuilderCustomizableContext:                  addNode(java.lang.String):anno 0 java.lang.Deprecated()
javax.validation.ConstraintValidatorContext$ConstraintViolationBuilder$NodeBuilderDefinedContext:   addNode(java.lang.String):anno 0 java.lang.Deprecated()
javax.validation.ConstraintValidatorContext$ConstraintViolationBuilder$NodeContextBuilder:          addNode(java.lang.String):anno 0 java.lang.Deprecated()
signatures:
```

As per the the Java EE [compatability rules](https://java.net/projects/javaee-spec/pages/CompatibilityRequirements) one must not add `@Deprecated` annotations. We also had them originally (pre 1.1 Final) but then removed them as per these rules.

Do you think you could trigger the release of an updated _javaee-api_ JAR, removing these annotations?

**Comment by rmannibucau** [comment]
Will try to do the geronimo-validation this week and javaee-api with tomee 7.0.2 (hopefully ~ this month)

**Comment by gunnarmorling** [comment]
Cool, thanks! Other than that all looks good, so as soon as we have the updated JARs I'll put you on the website.

**Comment by gunnarmorling** [comment]
Hey @rmannibucau, did you have a chance to create a new version of your spec JAR?

**Comment by rmannibucau** [comment]
Yes, TomEE 7.0.2 should have the javaee-api 7.0-1 which should contain this fix

**Comment by gunnarmorling** [comment]
Thanks, @rmannibucau!

Tested with TomEE 7.0.2 and javaee-api 7.0-1. All looking good. Prepared the website change [here](https://github.com/beanvalidation/beanvalidation.org/pull/50).

**Comment by rmannibucau** [comment]
Awesome, thanks a lot @gunnarmorling!

**Comment by gunnarmorling** [comment]
And there it is: http://beanvalidation.org/news/2017/02/07/apache-bval-is-compatible-with-bean-validation-1-1/
