### ISSUE TITLE
Update proposal list

### ISSUE THREAD

**Issue by hendrikebbers** [beanvalidation/beanvalidation.org#37]
http://beanvalidation.org/proposals/ do not contain a full list of all proposals that are part of this repo.

Missing proposals should be added to proposals/index.md

**Comment by gunnarmorling** [comment]
Good catch, but watch out that some proposals are actually stale and probably should be rather removed.

**Comment by hendrikebbers** [comment]
mmh, this should be discussed in the mailing list. Do not want to decide this alone :) I will write a mail links to all proposals and collect the old ones. In that case the md files should be removed

**Comment by gunnarmorling** [comment]
Done.
