### ISSUE TITLE
Provide better navigation and separation between BV 1.0, 1.1 and 2.0 resources

### ISSUE THREAD

**Issue by gunnarmorling** [beanvalidation/beanvalidation.org#61]
The biggest problem is that the top level menu only references 1.1 pages, even if a 1.0 page is displayed. 1.0 and 1.2 should be better separated on the site.

**Comment by gunnarmorling** [comment]
Migrated from https://hibernate.atlassian.net/browse/BVAL-481

**Comment by gsmet** [comment]
Fixed this one with the new website layout.
