### ISSUE TITLE
Add a list of 3rd party constraints

### ISSUE THREAD

**Issue by gunnarmorling** [beanvalidation/beanvalidation.org#66]
* HV custom constraints
* https://github.com/nomemory/java-bean-validation-extension
* https://github.com/jirutka/validator-collection
* https://github.com/malkusch/validation
* (https://github.com/Baeldung/spring-security-registration/blob/master/src/main/java/org/baeldung/validation/PasswordConstraintValidator.java)

**Comment by gsmet** [comment]
Fixed with: https://github.com/beanvalidation/beanvalidation.org/commit/96a8b9172d00c336953ebb26dd37e86b9234fea0
