### ISSUE TITLE
Question about `resources.md` for third party constraints.

### ISSUE THREAD

**Issue by Naoghuman** [beanvalidation/beanvalidation.org#67]
Hi,
@gunnarmorling ask me in `Twitter` if I want to make a PR if I like to be in your 3rd party list for `Bean Validation 2.0` constraints.

I have started with a little JavaFX library which I plan for the future to extends with more constraints. Momentary I have 1 constraint there: `NewDuration(Validator)` which allowed to check if a `LocalDateTime` is in a given `Duration` (days), so I can flag entities as `New` for example in the navigation from an application.

My project: https://github.com/Naoghuman/lib-validation
Project description: Lib-Validation is a library for `easy` validating in a JavaFX & Maven application during the integration from [Bean Validation 2.0] (JSR 380). 

So before I do a `PR` I should know how the new entry should be formulated?
Should I point to the momentary only one existing constraint `NewDuration` or to the library which will contain in future more constraint then one? 

Like the two last entries in:
### For Bean Validation 2.0 (JSR 380)

 * [The validation project of Markus Malkusch](https://github.com/malkusch/validation) provides another set of constraints (`@BitcoinAddress`, `@ISBN`...).
 * [A nice example of password validator](https://github.com/Baeldung/spring-security-registration/blob/master/src/main/java/org/baeldung/validation/PasswordConstraintValidator.java) based on [Passay](http://www.passay.org/), a password policy enforcement library.

**Comment by gunnarmorling** [comment]
If you're planning to add more constraints soon, I'd suggest to point to the library.

**Comment by Naoghuman** [comment]
Sure, with the next release I planed a new constraint and also examples for the usage from both then in the documentation.
After the work I will post a suggestion for the new entry.

**Comment by gsmet** [comment]
Thanks Peter. Looking forward to it. Closing this one, please open a PR when fitted.
