### ISSUE TITLE
Automatic deployment from CI no longer works

### ISSUE THREAD

**Issue by yrodiere** [beanvalidation/beanvalidation.org#83]
See title: when I push to this repo, the corresponding job on ci.hibernate.org doesn't get triggered.

I think there's something wrong with the GitHub webhooks, but I don't have access to settings on this repo.

@gsmet could you please check that the webhooks on this repo match the ones on https://github.com/hibernate/hibernate.org ?

**Comment by yrodiere** [comment]
@gsmet Bump, just in case this got lost in your big pile of emails :)

**Comment by gsmet** [comment]
It should be OK now, thanks for pinging me!
